source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

xcodeproj 'MBCircularProgressBar'
use_frameworks!

target 'MBCircularProgressBar_Example' do
    pod 'MBCircularProgressBar', :path => '../'
end

target 'MBCircularProgressBar_Tests' do
    pod 'MBCircularProgressBar', :path => '../'
end
