source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MBCircularProgressBar_Example', :exclusive => true do
  pod "MBCircularProgressBar", :path => "../"
end

target 'MBCircularProgressBar_Tests', :exclusive => true do
  pod "MBCircularProgressBar", :path => "../"

  
end
